Разрешить не называть возвращаемое значение $result
roistat/php-code-conventions pull request #30
Opened 2018-12-17 14:19 UTC by kzon

2018-12-17 14:28 UTC, flrnull requested changes

2018-12-17 14:28 UTC, flrnull commented on README.md
> +### 📖 В больших методах возвращаемая переменная должна называться `$result`
А что такое "большой метод"? Нет четких критериев у правила.

2018-12-18 10:10 UTC, kzon commented on README.md
> +### 📖 В больших методах возвращаемая переменная должна называться `$result`
@flrnull поправил

2018-12-18 10:19 UTC, flrnull commented on README.md
> +### 📖 В больших методах возвращаемая переменная должна называться `$result`
@kzon ну что-то у тебя странное там. То ты пишешь, что в больших методах переменная должна быть $result. А потом в примере пишешь обратное

2018-12-19 11:22 UTC, kzon commented on README.md
> +### 📖 В больших методах возвращаемая переменная должна называться `$result`
@flrnull вроде в примерах все логично. Плохо называть $users, если метод большой, хорошо назвать $result.

2018-12-19 11:46 UTC, merged