Flags in objects and constructors
roistat/php-code-conventions pull request #37
Opened 2020-07-21 17:38 UTC by slyshkin

2020-07-21 17:39 UTC, slyshkin commented
@flrnull добавил про флаги

2020-07-21 17:44 UTC, flrnull requested changes

2020-07-21 17:44 UTC, flrnull commented on README.md
> +    public function __construct(string $state) {
А почему вдруг текстовое поле стало плохим?

2020-07-21 17:56 UTC, slyshkin commented on README.md
> +    public function __construct(string $state) {
@flrnull здесь же как раз в нем нет смысла, так как оно принимает одно из двух значений, если мы, конечно, не учитываем состояние суперпозиции, а уже открыли коробку с котом :)

2020-07-21 18:22 UTC, flrnull commented on README.md
> +    public function __construct(string $state) {
В state может быть что угодно. 
Если тут имелся в виду bool, то надо добавить тогда кода с константами и прочим. Но я не вижу в этом смысла. Достаточно просто в хороших вариантах оставить кейс и всё

2020-07-21 18:34 UTC, slyshkin commented on README.md
> +    public function __construct(string $state) {
@flrnull поправил

2020-07-21 21:58 UTC, flrnull requested changes

2020-07-21 21:58 UTC, flrnull commented on README.md
> +Хорошо:
А зачем еще один блок "Хорошо"? Почему не в существующем?

2020-07-22 15:19 UTC, slyshkin commented on README.md
> +Хорошо:
@flrnull исправил

2020-07-22 15:24 UTC, flrnull requested changes

2020-07-22 15:24 UTC, flrnull commented on README.md
> +```php
Ты почти смог))

2020-07-22 16:13 UTC, slyshkin commented on README.md
> +```php
@flrnull а теперь?

2020-07-22 16:22 UTC, flrnull approved these changes

2020-07-22 16:22 UTC, merged